### ISSUE TITLE
Adding Gitter channels for student queries

### ISSUE THREAD

**Issue by daminisatya** [salesforce/gsoc#4]
Adding Gitter channels for each of the project (I see there's one existing for TransmogrifAI) helps in dealing with student queries. Having a common email ID is definitely not a great idea, because often you receive a lot of redundant queries from students. 

If they exist, then we must definitely add the links over here to direct students to the correct place to discussions.

**Comment by daminisatya** [comment]
@amateurhuman @interactivellama @tovbinm

**Comment by tovbinm** [comment]
Thanks for the suggestion. I found email to be the most reliable way of communicating and it also sets the correct excpection of not getting an immediate response.
