### ISSUE TITLE
Number of projects

### ISSUE THREAD

**Issue by ashwath7500** [salesforce/gsoc#8]
"Model interpretability/explainability", "Hyperparameter optimization" and "Developer Experience" under transmogrifAI are 3 different projects or just one ?

**Comment by tanhengyeow** [comment]
My best guess is that `TransmogrifAI` is the project you will be working on and the ones you mentioned are 3 different proposals for `TransmogrifAI`. 

Each proposal targets different things to work for `TransmogrifAI` 😄

**Comment by interactivellama** [comment]
Those are project ideas within one project. A final proposal could be one idea, multiple ideas, etc.
